#!/bin/bash
clear
PS3='What do you want to do?: '
options=("Stop all socat services" "Stop one particular socat service" "Quit")
select opt in "${options[@]}"
do
    case $opt in
        "Stop all socat processes")
            clear
            echo "Stopping all socat services"
            pkill -9 axttyd
            echo "Done."
            exit
            ;;
        "Stop one particular axel process")
            clear
            echo "Which socat service number to do you wish to stop?"
            read varname
            echo "Killing socat service $varname"
            pkill -9 axttyd$varname
            echo "Done."
            exit
            ;;
        "Quit")
            break
            exit
            ;;
        *) echo "invalid option $REPLY";;
    esac
done
